name: terraform deploy
on:
 merge_group:
 pull_request:
 workflow_dispatch:
    branches:
     - main
     - 'DSOMON-**'
  
    inputs:
      Terraform_Workspace_Name:
        description: Select the Environment. Default - (Dso-sandbox)
        required: true
        default: dso-sandbox
        type: choice
        options:
        - sandbox
      
      
      task:
        description: Select the task to perform. Default - (View TF Plan)
        required: false
        default: View Terraform Plan
        type: choice
        options:
        - View Terraform Plan
        - Perform Terraform Apply

      apply:
        description: Confirmation for Terraform Apply. Default - (False)
        required: false
        default: false
        type: choice
        options:
        - true
        - false
       
    env:
      TERRAFORM_WORKSPACE_NAME: {inputs.Terraform_Workspace_Name}
      TASK: {inputs.task}
      APPLY : {inputs.apply}

      
        
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: deploy

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: write

    steps:     
      - name: Checkout
        uses: actions/checkout@v3

      
      - name: Runtime Parameters Display
        run: |
          echo "Below is the summary of inputs provided :"
          echo "Environment Selected : ${{ inputs.TERRAFORM_WORKSPACE_NAME }}" 
          echo "Task to perform : ${{ inputs.TASK }}"
          echo "Confirmation to apply : ${{ inputs.APPLY }}"
          
